# Generated by Django 5.0.2 on 2024-03-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=150, verbose_name='имя'),
        ),
    ]
