# Generated by Django 5.0.2 on 2024-03-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
